### ISSUE TITLE
[Overview] lantiq-avm3370: Device Integration Checklist

### ISSUE THREAD

**Issue by dzzinstant** [dzzinstant/gluon#2]
### Device Integration Checklist
- [x] must be flashable from vendor firmware
   ( ) webinterface
   ( ) tftp
  - [x] other: ftp [EVA bootloader, separate images for kernel and filesystem partitions] -> https://github.com/dzzinstant/gluon/issues/3
- [x] must support upgrade mechanism
  - [x] must have working sysupgrade
    - [x] must keep/forget configuration (if applicable)
      *think `sysupgrade [-n]` or `firstboot`*
  - [x] must have working autoupdate
  _usually means: gluon profile name must match image name_
  ```
  :~# lua -e 'print(require("platform_info").get_image_name())'
  avm-fritz-box-3370-rev-2-hynix-nand
  ```
- [ ] reset/wps/phone button must return device into config mode [no such button => use 'power' button instead] -> https://github.com/dzzinstant/gluon/commit/7ba5577eac5146fc8df3b669cd3c10a96e0ad0a1
- [x] primary mac should match address on device label (or packaging) (https://gluon.readthedocs.io/en/latest/dev/hardware.html#notes)
- wired network
  - [x] should support all network ports on the device
  - [ ] must have correct port assignment (WAN/LAN) [numbering of LAN ports is mixed up, does that matter?] -> https://github.com/dzzinstant/gluon/issues/4
- wifi (if applicable)
  - [x] association with AP must be possible on all radios
  - [x] association with 802.11s mesh must be working on all radios 
  - [x] ap/mesh mode must work in parallel on all radios
- led mapping
  - power/sys led (_critical, because led definitions are setup on firstboot only_)
    - [x] lit while the device is on
    - [x] should display config mode blink sequence
(https://gluon.readthedocs.io/en/latest/features/configmode.html)
  - radio leds
    - [x] should map to their respective radio
    - [x] should show activity
  - switchport leds
    - [x] should map to their respective port (or switch, if only one led present) 
    - [ ] should show link state and activity [shows only state, maybe apply patch to also show activity] -> https://github.com/dzzinstant/gluon/commit/84fe9fc1a0d9642b84f7bda9077f4b8038a1dfc4
- outdoor devices only
  ( ) added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`

**Additional / device-specific**
- [x] wan-radio/private wlan [can be enabled in parallel with client + mesh wlan]
- [ ] 'WLAN' button enables/disables radio -> https://github.com/openwrt/openwrt/pull/3042
- [ ] also works in the 5 Ghz band [3370 only has a single radio for both bands]
  - [x] association with AP must be possible
  - [x] association with 802.11s mesh must be working (only indoor mode)
  - [x] ap/mesh mode must work in parallel (only indoor mode)
  - [ ] outdoor mode with DFS [basically works, but some clients cause false radar detections]
